### ISSUE TITLE
创建数据库提示无法导入文件

### ISSUE THREAD

**Issue by 52lemon** [honmaple/maple-bbs#21]
`
Traceback (most recent call last):
  File "runserver.py", line 19, in <module>
    from forums import create_app
  File "F:\PycharmProjects\maple-bbs\forums\__init__.py", line 19, in <module>
    from forums import api, docs, admin
  File "F:\PycharmProjects\maple-bbs\forums\api\__init__.py", line 13, in <module>
    from forums.api.forums import urls as forums_url
ImportError: No module named api.forums
`

**Comment by honmaple** [comment]
这应该是python版本的原因，我使用的是python3, python2使用的话会有很多问题

**Comment by 52lemon** [comment]
问题已经处理了，是python版本的问题

**Comment by 52lemon** [comment]
直接访问forums.localhost:8000 访问失败，不知道是什么原因
