### ISSUE TITLE
Python3报错？

### ISSUE THREAD

**Issue by iHTCboy** [honmaple/maple-bbs#31]
```
(venv) ➜  maple-bbs git:(master) ✗ python runserver.py initdb
/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask_caching/__init__.py:184: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
(venv) ➜  maple-bbs git:(master) ✗ python runserver.py create_index
/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask_caching/__init__.py:184: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
Usage: runserver.py [OPTIONS] COMMAND [ARGS]...
Try "runserver.py --help" for help.

Error: No such command "create_index".
(venv) ➜  maple-bbs git:(master) ✗ 
(venv) ➜  maple-bbs git:(master) ✗ 
(venv) ➜  maple-bbs git:(master) ✗ python runserver.py create_user
/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask_caching/__init__.py:184: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
Usage: runserver.py [OPTIONS] COMMAND [ARGS]...
Try "runserver.py --help" for help.

Error: No such command "create_user".
(venv) ➜  maple-bbs git:(master) ✗
(venv) ➜  maple-bbs git:(master) ✗
(venv) ➜  maple-bbs git:(master) ✗python runserver.py
Connected to pydev debugger (build 183.5429.31)
/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask_caching/__init__.py:184: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
 * Serving Flask app "runserver"
 * Forcing debug mode off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


127.0.0.1 - - [05/Jun/2019 17:50:03] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [05/Jun/2019 17:50:04] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [05/Jun/2019 17:54:43] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [05/Jun/2019 17:54:45] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [05/Jun/2019 17:54:52] "GET /index.html HTTP/1.1" 404 -
127.0.0.1 - - [05/Jun/2019 17:54:54] "GET /index.html HTTP/1.1" 404 -

```

![image](https://user-images.githubusercontent.com/11418363/58947774-376c7680-87bb-11e9-8e1a-7af322523146.png)

请问，这个是什么原因啊？谢谢~

**Comment by honmaple** [comment]
404是因为默认使用子域名，所以只能访问`forums.localhost:8000`

`Error: No such command "create_index".`这可能是`click`版本的原因，使用`python runserver.py --help`查看现有命令

**Comment by iHTCboy** [comment]
@honmaple  你好，感谢回复啊
问题1（已经解决）：
命令改为：
```
python runserver.py create-index
python runserver.py create-user 
```
就可以啦。

问题2：
`未解决`
404是因为默认使用子域名，所以只能访问forums.localhost:8000

我换成了 `forums.localhost:8000` 还是一样 显示 404

我想了解一下 `gunicorn.conf` 是不是要配置 gunicorn？ 这个我没有用过，新手啊。

我用PyCharm 打开的：
```

FLASK_APP = runserver.py
FLASK_ENV = development
FLASK_DEBUG = 0
In folder /Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs
/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/bin/python /Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py --module --multiproc --qt-support=auto --client 127.0.0.1 --port 64559 --file flask run
pydev debugger: process 38137 is connecting

Connected to pydev debugger (build 183.5429.31)
/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask_caching/__init__.py:184: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
 * Serving Flask app "runserver"
 * Forcing debug mode off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

然后改成： `forums.localhost:5000` 打开也是 404

![image](https://user-images.githubusercontent.com/11418363/58950866-54f10e80-87c2-11e9-8ccb-1185d54c7338.png)

**Comment by honmaple** [comment]
最简单的`gunicorn.conf`可以这样
```
debug = True
loglevel = 'debug'
workers = 2
bind = "127.0.0.1:8000"
threads = 4
```
然后使用`gunicorn runserver:app -c gunicorn.conf`运行，但这样也是访问`forums.localhost:8000`

404的原因你需要检查一下`config.py`里的配置，主要是这两行
```
SERVER_NAME = 'localhost:8000'
SUBDOMAIN = {'forums': True, 'docs': False}
```
如果访问还是404, 子域名设置为False，然后访问`localhost:8000`

**Comment by iHTCboy** [comment]
@honmaple 好的，谢谢大佬！

问题2已经解决。 使用`gunicorn runserver:app -c gunicorn.conf`运行可以打开啦。

问题3：
注册时，图片验证码显示不了：
```

[2019-06-06 11:28:54 +0800] [44791] [DEBUG] GET /captcha
[2019-06-06 11:28:54 +0800] [44791] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 279, in handle
    keepalive = self.handle_request(req, conn)
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 348, in handle_request
    six.reraise(*sys.exc_info())
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/gunicorn/six.py", line 625, in reraise
    raise value
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 328, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/werkzeug/middleware/proxy_fix.py", line 228, in __call__
    return self.app(environ, start_response)
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask_maple/captcha.py", line 41, in _response
    buf = t.start(font_type=self.font)
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask_maple/captcha.py", line 129, in start
    code_img = self.create_validate_code()
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask_maple/captcha.py", line 78, in create_validate_code
    width, height, fg_color)
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/flask_maple/captcha.py", line 114, in create_strs
    font = ImageFont.truetype(font_type, font_size)
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/PIL/ImageFont.py", line 280, in truetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/Volumes/APPLE-HDD/Document/Coding/Python/maple-bbs/venv/lib/python3.7/site-packages/PIL/ImageFont.py", line 145, in __init__
    layout_engine=layout_engine)
OSError: cannot open resource

```

![image](https://user-images.githubusercontent.com/11418363/59004991-55cf8200-884e-11e9-8a06-a70d5f665f9f.png)
![image](https://user-images.githubusercontent.com/11418363/59005064-a941d000-884e-11e9-98b4-bc6123f0f692.png)

这个可能是我这个 `PIL` 版本不对吗？

**Comment by honmaple** [comment]
验证码字体不存在，默认使用`/usr/share/fonts/TTF/DejaVuSans.ttf`，如果没有需要手动传递字体路径，修改`forums/extension/maple.py`里的`Captcha(app)`
```
Captcha(app, font="字体路径")
```

**Comment by iHTCboy** [comment]
@honmaple  谢谢大佬，问题都解决啦！现在能跑起来啦！

我还需要自己多学习啊，能google的我都知道先试试，没有想到还有这么多知识空白，感谢啦！thanks！

另外，才入门 flask ，对正式部署也不了解，有没有会推荐学习的资料吗？

**Comment by honmaple** [comment]
正式部署的话可以搜索nginx + flask + gunicorn
