### ISSUE TITLE
cannot import name bootstrap from flask-maple

### ISSUE THREAD

**Issue by patchouli-exarch** [honmaple/maple-bbs#33]
python runserver.py时遇到的：

Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from maple import create_app
  File "C:\maple-bbs-release-v1\maple\__init__.py", line 15, in <module>
    from maple.auth.views import register_auth
  File "C:\maple-bbs-release-v1\maple\auth\views.py", line 14, in <module>
    from maple.extension import mail, redis_data
  File "C:\maple-bbs-release-v1\maple\extension.py", line 23, in <module>
    from flask_maple import Bootstrap, Error, Captcha
ImportError: cannot import name 'Bootstrap' from 'flask_maple' (C:\ProgramData\A
naconda3\lib\site-packages\flask_maple\__init__.py)

**Comment by honmaple** [comment]
`release-v1` no longer support. Use master instead of it.

**Comment by patchouli-exarch** [comment]
fine, thank you very much!
