### ISSUE TITLE
执行 python3 runserver.py initdb报错

### ISSUE THREAD

**Issue by chengzequn** [honmaple/maple-bbs#38]
Traceback (most recent call last):
  File "runserver.py", line 19, in <module>
    from forums import create_app
  File "/root/maple-bbs/forums/__init__.py", line 17, in <module>
    from forums import app as ap, extension
  File "/root/maple-bbs/forums/extension/__init__.py", line 22, in <module>
    from . import babel, login, maple
  File "/root/maple-bbs/forums/extension/maple.py", line 25, in <module>
    use_auth=True)
TypeError: __init__() got an unexpected keyword argument 'use_auth'

**Comment by honmaple** [comment]
`flask-maple`版本问题，具体参考requirements.txt
