### ISSUE TITLE
您好，我在ubuntu14.04系统下搭建了您的项目，搭建结束运行时，网页出现了一下问题，请问我要怎么解决？

### ISSUE THREAD

**Issue by wangmingYu1212** [honmaple/maple-bbs#7]
redis.exceptions.ResponseError

redis.exceptions.ResponseError: Client sent AUTH, but no password is set
Traceback (most recent call last)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/app.py", line 2000, in __call__

    return self.wsgi_app(environ, start_response)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/app.py", line 1991, in wsgi_app

    response = self.make_response(self.handle_exception(e))

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/app.py", line 1567, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise

    raise value

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app

    response = self.full_dispatch_request()

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise

    raise value

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/app.py", line 1637, in full_dispatch_request

    rv = self.preprocess_request()

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/app.py", line 1837, in preprocess_request

    rv = func()

    File "/home/wmy/maple-bbs-master/forums/common/middleware.py", line 49, in preprocess_request

    mark_online(request.remote_addr)

    File "/home/wmy/maple-bbs-master/forums/common/records.py", line 38, in mark_online

    high = redis_data.hget('online_users', 'high:counts')

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/redis/client.py", line 1857, in hget

    return self.execute_command('HGET', name, key)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/redis/client.py", line 572, in execute_command

    connection.send_command(*args)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/redis/connection.py", line 563, in send_command

    self.send_packed_command(self.pack_command(*args))

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/redis/connection.py", line 538, in send_packed_command

    self.connect()

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/redis/connection.py", line 446, in connect

    self.on_connect()

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/redis/connection.py", line 514, in on_connect

    if nativestr(self.read_response()) != 'OK':

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/redis/connection.py", line 582, in read_response

    raise response

    redis.exceptions.ResponseError: Client sent AUTH, but no password is set

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object

Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by honmaple** [comment]
redis密码错误

**Comment by wangmingYu1212** [comment]
redis配置好了  页面又显示404了，请问想要配置运行这个工程，我还要需要配置哪些文件呢？

**Comment by honmaple** [comment]
如果你是在本地运行，应该访问 `forums.localhost:5000`

**Comment by wangmingYu1212** [comment]
访问 forums.localhost:5000就提示找不到服务器。。。请问除了您在readme所说的步骤，我还需要修改别的配置文件么？

**Comment by honmaple** [comment]
你改一下配置文件 `SERVER_NAME = 'localhost:8000'`，然后访问`forums.localhost:8000` ,或者把runserver.py里的`app.run(port=8000)`端口删除应该就可以了

**Comment by honmaple** [comment]
后台这里有个问题,我已修复[https://github.com/honmaple/maple-bbs/commit/f922a471e5728e5d123e124b490ad760b90fb9a5](https://github.com/honmaple/maple-bbs/commit/f922a471e5728e5d123e124b490ad760b90fb9a5)，你可以手动更改一下

**Comment by wangmingYu1212** [comment]
按照您教的方式做了，删除了runserver.py的端口8000，重启了server，还是不行还是无法链接到 forums.localhost 的服务器。我没对您的代码进行改动

**Comment by wangmingYu1212** [comment]
项目搭建成功，在搜索框中，点击搜索，页面显示AttributeError: 'Query' object has no attribute 'msearch'

**Comment by honmaple** [comment]
抱歉，这是因为 `flask-msearch`版本问题，`pip install flask-msearch --upgrade`就行

**Comment by wangmingYu1212** [comment]
您好，又打扰您了，点击提出问题后，输入问题，按格式填写成功后，点击提交，页面自动刷新，但是为什么首页不显示我发出的那个帖子呢？还有点击首页文档的那个框，提示我们无法连接至 docs.localhost 的服务器

**Comment by honmaple** [comment]
第一个应该是缓存的原因，第二个启用了docs子域名，设置 `SUBDOMAIN = {'forums': False, 'docs': False}`可以关闭

**Comment by wangmingYu1212** [comment]
提问题发帖时，分类框中不显示东西，没法选择分类，但不选择又不能提交问题，请问怎么解决呀？

**Comment by honmaple** [comment]
你需要进入后台添加版块信息

**Comment by wangmingYu1212** [comment]
当有一个分类信息时，再添加另一个分类会出现以下错误，请问您我该怎么解决？删除已有的分类时候，也会报错
builtins.ValueError

ValueError: too many values to unpack (expected 2)
Traceback (most recent call last)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/app.py", line 1997, in __call__

    return self.wsgi_app(environ, start_response)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__

    return self.app(environ, start_response)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/app.py", line 1985, in wsgi_app

    response = self.handle_exception(e)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/app.py", line 1540, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise

    raise value

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app

    response = self.full_dispatch_request()

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise

    raise value

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request

    rv = self.dispatch_request()

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/base.py", line 69, in inner

    return self._run_view(f, *args, **kwargs)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/base.py", line 368, in _run_view

    return fn(self, *args, **kwargs)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/model/base.py", line 1947, in create_view

    return_url=return_url)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/base.py", line 308, in render

    return render_template(template, **kwargs)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/templating.py", line 134, in render_template

    context, ctx.app)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask/templating.py", line 116, in _render

    rv = template.render(context)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render

    return self.environment.handle_exception(exc_info, True)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise

    raise value.with_traceback(tb)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/templates/bootstrap3/admin/model/create.html", line 3, in top-level template code

    {% from 'admin/lib.html' import extra with context %} {# backward compatible #}

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/templates/bootstrap3/admin/master.html", line 1, in top-level template code

    {% extends admin_base_template %}

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 30, in top-level template code

    {% block page_body %}

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 70, in block "page_body"

    {% block body %}{% endblock %}

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/templates/bootstrap3/admin/model/create.html", line 22, in block "body"

    {% block create_form %}

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/templates/bootstrap3/admin/model/create.html", line 23, in block "create_form"

    {{ lib.render_form(form, return_url, extra(), form_opts) }}

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/jinja2/runtime.py", line 579, in _invoke

    rv = self._func(*arguments)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 202, in template

    {% call form_tag(action=action) %}

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/jinja2/runtime.py", line 579, in _invoke

    rv = self._func(*arguments)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 182, in template

    {{ caller() }}

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/jinja2/runtime.py", line 579, in _invoke

    rv = self._func(*arguments)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 203, in template

    {{ render_form_fields(form, form_opts=form_opts) }}

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/jinja2/runtime.py", line 579, in _invoke

    rv = self._func(*arguments)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 175, in template

    {{ render_field(form, f, kwargs) }}

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/jinja2/runtime.py", line 579, in _invoke

    rv = self._func(*arguments)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 130, in template

    {{ field(**kwargs)|safe }}

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/wtforms/fields/core.py", line 153, in __call__

    return self.meta.render_field(self, kwargs)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/wtforms/meta.py", line 56, in render_field

    return field.widget(field, **render_kw)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/form/widgets.py", line 28, in __call__

    return super(Select2Widget, self).__call__(field, **kwargs)

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/wtforms/widgets/core.py", line 287, in __call__

    for val, label, selected in field.iter_choices():

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/contrib/sqla/fields.py", line 110, in iter_choices

    for pk, obj in self._get_object_list():

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/contrib/sqla/fields.py", line 103, in _get_object_list

    self._object_list = [(text_type(get_pk(obj)), obj) for obj in query]

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/contrib/sqla/fields.py", line 103, in <listcomp>

    self._object_list = [(text_type(get_pk(obj)), obj) for obj in query]

    File "/home/wmy/maple-bbs-master/py3env/lib/python3.4/site-packages/flask_admin/contrib/sqla/fields.py", line 300, in get_pk_from_identity

    cls, key = identity_key(instance=obj)

    ValueError: too many values to unpack (expected 2)

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object

Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by honmaple** [comment]
SQLAlchemy版本问题，`pip install SQLAlchemy==1.1.6`，具体原因可自行搜索

**Comment by honmaple** [comment]
reopen if needed
